/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFormItems: typeof import('./../src/components/app/form/items.vue')['default']
    AppHeaderItem: typeof import('./../src/components/app/header-item.vue')['default']
    AppSider: typeof import('./../src/components/app/sider.vue')['default']
    IChevronLeft: typeof import('~icons/tabler/chevron-left')['default']
    IChevronRight: typeof import('~icons/tabler/chevron-right')['default']
    IChevronRightFilled: typeof import('~icons/tabler/chevron-right-filled')['default']
    IForms: typeof import('~icons/tabler/forms')['default']
    IHelp: typeof import('~icons/tabler/help')['default']
    IHelpCircle: typeof import('~icons/tabler/help-circle')['default']
    IHome: typeof import('~icons/tabler/home')['default']
    IHome2: typeof import('~icons/tabler/home2')['default']
    IInfo: typeof import('~icons/tabler/info')['default']
    ILayoutSidebarLeftExpand: typeof import('~icons/tabler/layout-sidebar-left-expand')['default']
    ILayoutSidebarRightExpand: typeof import('~icons/tabler/layout-sidebar-right-expand')['default']
    IMenu: typeof import('~icons/tabler/menu')['default']
    IMenu2: typeof import('~icons/tabler/menu2')['default']
    ISquareRoundedChevronLeftFilled: typeof import('~icons/tabler/square-rounded-chevron-left-filled')['default']
    ISquareRoundedChevronRightFilled: typeof import('~icons/tabler/square-rounded-chevron-right-filled')['default']
    ITable: typeof import('~icons/tabler/table')['default']
    ITableFilled: typeof import('~icons/tabler/table-filled')['default']
    IX: typeof import('~icons/tabler/x')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
